<?php
class UserController extends \App\Http\Controllers\Controller
{


    public function __call($method, $parameters)
    {
        parent::__call($method, $parameters); // TODO: Change the autogenerated stub
    }


}
